# Generated by Django 3.0.8 on 2020-07-27 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InvestigatorRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=255)),
                ('Definition', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('MiddleName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.InvestigatorRank')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('FireOutDateTime', models.DateTimeField()),
                ('HouseNumber', models.CharField(max_length=255)),
                ('Street', models.CharField(max_length=255)),
                ('OccupancyType', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=255)),
                ('OwnerEstablishmentName', models.CharField(max_length=255)),
                ('ALARM_LEVEL_CHOICES', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=1)),
                ('Injuries', models.IntegerField()),
                ('FatalitiesMale', models.IntegerField()),
                ('FatalitiesFemale', models.IntegerField()),
                ('TotalFatalities', models.IntegerField()),
                ('EstimatedDamageCost', models.IntegerField()),
                ('FinalDamageCost', models.IntegerField()),
                ('Origin', models.CharField(max_length=255)),
                ('Cause', models.TextField()),
                ('Remarks', models.TextField()),
                ('Barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Barangay')),
                ('FireArsonInvestigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Investigator')),
            ],
        ),
    ]
