# Generated by Django 3.0.8 on 2020-07-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='ALARM_LEVEL_CHOICES',
            new_name='AlarmLevel',
        ),
        migrations.AddField(
            model_name='incident',
            name='Notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='incident',
            name='Remarks',
            field=models.CharField(choices=[('closed', 'Closed'), ('under investigation', 'Under Investigation')], default='closed', max_length=255),
        ),
    ]
