# Generated by Django 3.0.8 on 2020-07-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200728_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigatorrank',
            name='Definition',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
