# Generated by Django 3.0.8 on 2020-07-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200728_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='Cause',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='EstimatedDamageCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='incident',
            name='FatalitiesFemale',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='incident',
            name='FatalitiesMale',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='incident',
            name='FinalDamageCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='incident',
            name='FireOutDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='HouseNumber',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='Injuries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='incident',
            name='Notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='incident',
            name='Origin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='Street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='TotalFatalities',
            field=models.IntegerField(default=0),
        ),
    ]
