# Generated by Django 3.0.8 on 2020-07-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200728_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='Latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='barangay',
            name='Longitude',
            field=models.IntegerField(default=0),
        ),
    ]
