# Generated by Django 3.0.8 on 2020-07-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200729_2010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investigator',
            unique_together={('FirstName', 'LastName')},
        ),
    ]
