# Generated by Django 3.0.8 on 2020-07-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200729_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='Latitude',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='Longitude',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
    ]
