# Generated by Django 3.0.8 on 2020-07-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200729_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigator',
            name='FirstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='LastName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='MiddleName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='investigatorrank',
            name='Code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='investigatorrank',
            name='Definition',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
