# Generated by Django 3.0.8 on 2020-07-30 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200729_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupancyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='incident',
            name='OccupancyType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.OccupancyType'),
        ),
    ]
