# Generated by Django 3.0.8 on 2020-07-30 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200730_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='Barangay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Barangay'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='FireArsonInvestigator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Investigator'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='OccupancyType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.OccupancyType'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='Remarks',
            field=models.CharField(blank=True, choices=[('closed', 'Closed'), ('under investigation', 'Under Investigation')], default='closed', max_length=255),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='Rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.InvestigatorRank'),
        ),
    ]
