# Generated by Django 3.0.8 on 2020-07-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200730_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
    ]
