# Generated by Django 3.0.8 on 2020-08-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200730_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='Name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='FirstName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='MiddleName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
