# Generated by Django 3.0.8 on 2020-08-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200803_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigatorrank',
            name='Code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='incident',
            unique_together={('DateTime', 'OwnerEstablishmentName')},
        ),
    ]
