# Generated by Django 3.0.8 on 2020-08-05 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200805_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='TotalFatalities',
        ),
    ]
