# Generated by Django 3.0.8 on 2020-08-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200805_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigator',
            name='FirstName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='MiddleName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
