# Generated by Django 3.0.8 on 2020-08-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200814_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='Notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
