# Generated by Django 3.0.8 on 2020-08-14 15:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200814_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='Location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
