# Generated by Django 3.0.8 on 2020-08-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_testdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='name_0',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='name_1',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='name_2',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='name_3',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
