# Generated by Django 3.0.8 on 2020-08-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20200822_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='varname_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
