# Generated by Django 3.0.8 on 2020-08-22 11:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_laguna'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Laguna',
        ),
        migrations.DeleteModel(
            name='TestData',
        ),
        migrations.RemoveField(
            model_name='barangay',
            name='Location',
        ),
        migrations.AddField(
            model_name='barangay',
            name='City',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='barangay',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='Name',
            field=models.CharField(max_length=75),
        ),
    ]
