# Generated by Django 3.0.8 on 2020-08-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20200822_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangay',
            name='City',
        ),
    ]
