# Generated by Django 3.0.8 on 2020-10-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_barangay_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='Approved',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
