# Generated by Django 3.0.8 on 2020-10-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_incident_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
    ]
