# Generated by Django 3.0.8 on 2020-12-25 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20201021_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barangay',
            options={'ordering': ('Name',)},
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ('Barangay',)},
        ),
        migrations.RemoveField(
            model_name='incident',
            name='FireOutDateTime',
        ),
    ]
