# Generated by Django 3.0.8 on 2020-12-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20201225_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ('DateTime', 'Barangay')},
        ),
        migrations.AddField(
            model_name='incident',
            name='EstablishmentName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='Owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='incident',
            unique_together={('DateTime', 'EstablishmentName', 'Owner')},
        ),
        migrations.RemoveField(
            model_name='incident',
            name='OwnerEstablishmentName',
        ),
    ]
