# Generated by Django 3.0.8 on 2020-12-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20201225_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ('-DateTime', 'Barangay')},
        ),
        migrations.AddField(
            model_name='incident',
            name='OwnerName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='incident',
            unique_together={('DateTime', 'OwnerName')},
        ),
        migrations.RemoveField(
            model_name='incident',
            name='Owner',
        ),
    ]
