# Generated by Django 3.0.8 on 2020-12-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20201225_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='OccupancyType',
        ),
    ]
