# Generated by Django 3.0.8 on 2020-12-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_remove_incident_occupancytype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OccupancyType',
        ),
    ]
