# Generated by Django 3.0.8 on 2020-12-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_delete_occupancytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='OccupancyType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
