# Generated by Django 3.0.8 on 2020-12-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20201225_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ('-DateAlarmReceived', 'Barangay')},
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='DateCalled',
            new_name='DateAlarmReceived',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='TimeCalled',
            new_name='TimeAlarmReceived',
        ),
        migrations.AddField(
            model_name='incident',
            name='Caller',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='ContactNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='incident',
            unique_together={('DateAlarmReceived', 'OwnerName')},
        ),
    ]
