# Generated by Django 3.0.8 on 2020-12-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20201226_0618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Investigator',
            new_name='Personnel',
        ),
        migrations.RenameModel(
            old_name='InvestigatorRank',
            new_name='Rank',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='ContactNumber',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='FireArsonInvestigator',
        ),
        migrations.AddField(
            model_name='incident',
            name='CallerAddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
