# Generated by Django 3.0.8 on 2020-12-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20201226_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Model', models.CharField(blank=True, max_length=255, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='incident',
            name='AlarmLevel',
        ),
        migrations.AddField(
            model_name='incident',
            name='DeathCivilianF',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incident',
            name='DeathCivilianM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incident',
            name='DeathFireFighterF',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incident',
            name='DeathFireFighterM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incident',
            name='DescriptionOfStructure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='DistanceFromBase',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incident',
            name='InjuredCivilianF',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incident',
            name='InjuredCivilianM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incident',
            name='InjuredFireFighterF',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incident',
            name='InjuredFireFighterM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incident',
            name='OccupancyTypeRemarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='PersonnelReceivingCall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Personnel'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='OccupancyType',
            field=models.CharField(blank=True, choices=[('Structural/Residential', 'Structural/Residential'), ('Non Structural', 'Non Structural'), ('Vehicular', 'Vehicular')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='IncidentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeDispatched', models.TimeField(blank=True, null=True)),
                ('TimeArrived', models.TimeField(blank=True, null=True)),
                ('TimeReturnedToBase', models.TimeField(blank=True, null=True)),
                ('WaterTankRefilled', models.IntegerField(default=0)),
                ('GasConsumed', models.IntegerField(default=0)),
                ('Engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Engines')),
                ('Incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Personnel')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd')], default='closed', max_length=255)),
                ('StatusRemarks', models.CharField(blank=True, max_length=255)),
                ('DateTimeUnderControl', models.DateTimeField(blank=True, null=True)),
                ('DateTimeFireOut', models.DateTimeField(blank=True, null=True)),
                ('Incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Personnel')),
            ],
        ),
    ]
