# Generated by Django 3.0.8 on 2020-12-26 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20201227_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmstatus',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='alarmstatus',
            name='StatusRemarks',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='FatalitiesFemale',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='FatalitiesMale',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='Notes',
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='GCommander1stAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='GCommander2ndAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='GCommander3rdAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='GCommander4thAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='GCommander5thAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='GCommanderAlphaAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='GCommanderBravoAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='GCommanderCharlieAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='GCommanderDeltaAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='GCommanderEchoAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='GCommanderGeneralAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='GCommanderHotelAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='GCommanderIndiaAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='StatusUponArrival',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd')], default='closed', max_length=255),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='StatusUponArrivalRemarks',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='Time1stAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='Time2ndAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='Time3rdAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='Time4thAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='Time5thAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='TimeAlphaAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='TimeBravoAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='TimeCharlieAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='TimeDeltaAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='TimeEchoAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='TimeGeneralAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='TimeHotelAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmstatus',
            name='TimeIndiaAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='BreathingApparatusNr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incident',
            name='BreathingApparatusType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='Details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='Observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='Problems',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alarmstatus',
            name='Incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Incident'),
        ),
        migrations.AlterField(
            model_name='incidentresponse',
            name='Incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Incident'),
        ),
        migrations.CreateModel(
            name='RopeAndLadder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=255)),
                ('Length', models.IntegerField(default=0)),
                ('Incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Incident')),
            ],
        ),
        migrations.CreateModel(
            name='HoseLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nr', models.IntegerField(default=0)),
                ('Type', models.CharField(blank=True, max_length=255)),
                ('Length', models.IntegerField(default=0)),
                ('Incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Incident')),
            ],
        ),
        migrations.CreateModel(
            name='ExtinguisingAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
                ('Type', models.CharField(blank=True, max_length=255)),
                ('Incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Incident')),
            ],
        ),
        migrations.CreateModel(
            name='DutyPersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(blank=True, max_length=255)),
                ('Remarks', models.CharField(blank=True, max_length=255)),
                ('Incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Incident')),
                ('Personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Personnel')),
            ],
        ),
    ]
