# Generated by Django 3.0.8 on 2020-12-27 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20201227_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='BreathingApparatusNr',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='BreathingApparatusType',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='Injuries',
        ),
        migrations.AddField(
            model_name='incident',
            name='Occupant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SpotInvestigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReportFor', models.CharField(blank=True, max_length=255)),
                ('ReportDate', models.DateField(blank=True, null=True)),
                ('Details', models.TextField(blank=True, null=True)),
                ('Disposition', models.TextField(blank=True, null=True)),
                ('Incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Incident')),
                ('NoteBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spot_noted', to='home.Personnel')),
                ('PreparedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spot_prepared', to='home.Personnel')),
            ],
        ),
        migrations.CreateModel(
            name='BreathingApparatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BreathingApparatusNr', models.IntegerField(default=0)),
                ('BreathingApparatusType', models.CharField(blank=True, max_length=255, null=True)),
                ('Incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Incident')),
            ],
        ),
        migrations.CreateModel(
            name='APOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Incident')),
                ('NoteBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apor_to', to='home.Personnel')),
                ('PreparedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apor_by', to='home.Personnel')),
            ],
        ),
    ]
