# Generated by Django 3.0.8 on 2020-12-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20201227_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(blank=True, max_length=255)),
                ('TelephoneNumber', models.CharField(blank=True, max_length=255)),
                ('PhoneNumbers', models.CharField(blank=True, max_length=255)),
                ('EmailAddress', models.EmailField(blank=True, max_length=254, null=True)),
                ('BFPLogo', models.ImageField(null=True, upload_to='')),
                ('StationLogo', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
