# Generated by Django 3.0.8 on 2020-12-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='DateTimeFireOut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='DateTimeUnderControl',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='GCommander1stAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='GCommander2ndAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='GCommander3rdAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='GCommander4thAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='GCommander5thAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='GCommanderAlphaAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='GCommanderBravoAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='GCommanderCharlieAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='GCommanderDeltaAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='GCommanderEchoAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='GCommanderGeneralAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='GCommanderHotelAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='GCommanderIndiaAlarm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='StatusUponArrival',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd')], default='closed', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='StatusUponArrivalRemarks',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='Time1stAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='Time2ndAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='Time3rdAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='Time4thAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='Time5thAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='TimeAlphaAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='TimeBravoAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='TimeCharlieAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='TimeDeltaAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='TimeEchoAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='TimeGeneralAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='TimeHotelAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='TimeIndiaAlarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AlarmStatus',
        ),
    ]
