# Generated by Django 3.0.8 on 2020-12-29 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alarmstatusuponarrival'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APOR',
        ),
    ]
