# Generated by Django 3.0.8 on 2020-12-29 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_delete_apor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alarmstatusuponarrival',
            unique_together={('Incident', 'StatusUponArrival')},
        ),
    ]
