# Generated by Django 3.0.8 on 2020-12-29 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_auto_20201229_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='StatusUponArrival',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='StatusUponArrivalRemarks',
        ),
    ]
