# Generated by Django 3.0.8 on 2020-12-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20201229_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmstatusuponarrival',
            name='StatusUponArrival',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd')], default='', max_length=255),
        ),
    ]
