# Generated by Django 3.0.8 on 2020-12-31 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_auto_20210101_0554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotInvestigation',
        ),
    ]
