# Generated by Django 3.0.8 on 2021-01-01 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_auto_20210101_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Rank'),
        ),
        migrations.AlterField(
            model_name='station',
            name='BFPLogo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='station',
            name='StationLogo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
