# Generated by Django 3.0.8 on 2021-01-02 09:39

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_auto_20210102_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='InvestigationDetails',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='Involved',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='TimeStarted',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
