# Generated by Django 3.0.8 on 2021-01-02 09:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_auto_20210102_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='Disposition',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
