# Generated by Django 3.0.8 on 2021-01-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_auto_20210104_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='Code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='incident',
            unique_together=set(),
        ),
    ]
