# Generated by Django 3.0.8 on 2021-01-04 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_auto_20210104_0929'),
        ('home', '0061_auto_20210104_0927'),
    ]

    operations = [
    ]
